name: Build R4S 1G 25.12.0-rc1 (2GB Rootfs)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python3 zstd

      - name: Download ImageBuilder
        run: |
          wget https://downloads.immortalwrt.org/releases/25.12.0-rc1/targets/rockchip/armv8/immortalwrt-imagebuilder-25.12.0-rc1-rockchip-armv8.Linux-x86_64.tar.zst
          tar -xf immortalwrt-imagebuilder-25.12.0-rc1-rockchip-armv8.Linux-x86_64.tar.zst
          mv immortalwrt-imagebuilder-25.12.0-rc1-rockchip-armv8.Linux-x86_64 builder

      - name: Build Firmware
        run: |
          cd builder
          make image PROFILE="friendlyarm_nanopi-r4s" PACKAGES="luci luci-i18n-base-zh-cn luci-app-homeproxy ppp ppp-mod-pppoe luci-compat" ROOTFS_PARTSIZE="2048"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt-R4S-25.12.0-rc1-2GB-Firmware
          path: builder/bin/targets/rockchip/armv8/*sysupgrade*.img.gz
